# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 12:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxa', '0001_initial'),
        ('people', '0001_initial'),
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('action_type', models.CharField(choices=[('R', 'Research'), ('C', 'Conservation')], max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('U', 'Underway'), ('P', 'Proposed'), ('C', 'Complete')], max_length=1, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlist.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('N', 'Regional (South Africa)'), ('R', 'Regional (Other)'), ('G', 'Global')], default='N', max_length=1)),
                ('date', models.DateField()),
                ('redlist_category', models.CharField(choices=[('EX', 'Extinct (EX)'), ('EW', 'Extinct in the Wild (EW)'), ('CR', 'Critically Endangered (CR)'), ('EN', 'Endangered (EN)'), ('VU', 'Vulnerable (VU)'), ('NT', 'Near Threatened (NT)'), ('LC', 'Least Concern (LC)'), ('DD', 'Data Deficient (DD)'), ('NE', 'Not Evaluated (NE)')], max_length=2)),
                ('redlist_criteria', models.CharField(max_length=100)),
                ('population_current', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('subpopulation_number', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('population_past', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('population_future', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('population_trend', models.CharField(blank=True, max_length=200, null=True)),
                ('population_trend_nature', models.CharField(blank=True, choices=[('U', 'Understood'), ('R', 'Reversible'), ('C', 'Ceased')], max_length=1, null=True)),
                ('area_occupancy', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('extent_occurrence', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('temp_field', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('population_trend_narrative', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('population_narrative', models.TextField(blank=True)),
                ('change_rationale', models.TextField(blank=True)),
                ('threats_narrative', models.TextField(blank=True)),
                ('conservation_narrative', models.TextField(blank=True)),
                ('research_narrative', models.TextField(blank=True)),
                ('use_trade_narrative', models.TextField(blank=True)),
                ('distribution_narrative', models.TextField(blank=True)),
                ('conservation_actions', models.ManyToManyField(to='redlist.Action')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('A', 'Assessor'), ('R', 'Reviewer'), ('C', 'Contributor'), ('F', 'Facilitator')], max_length=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlist.Assessment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'ordering': ['type', 'weight'],
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(blank=True, choices=[('EX', 'Extremely severe'), ('SE', 'Severe'), ('MO', 'Moderate'), ('SL', 'Slight'), ('NO', 'No decline'), ('UN', 'Unknown')], default='UN', max_length=2, null=True)),
                ('timing', models.CharField(blank=True, choices=[('PA', 'Past'), ('UR', 'Past, Unlikely to return'), ('LR', 'Past, Likely to return'), ('ON', 'Ongoing'), ('FU', 'Future'), ('PO', 'Potential'), ('UN', 'Unknown')], default='UN', max_length=2, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlist.Assessment')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlist.Threat')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='contributors',
            field=models.ManyToManyField(through='redlist.Contribution', to='people.Person'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='references',
            field=models.ManyToManyField(blank=True, to='biblio.Reference'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxa.Taxon'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='threats',
            field=models.ManyToManyField(through='redlist.ThreatNature', to='redlist.Threat'),
        ),
        migrations.AddField(
            model_name='actionnature',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlist.Assessment'),
        ),
    ]
