# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0002_auto_20170131_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionnature',
            name='status',
            field=models.CharField(blank=True, choices=[('U', 'Underway'), ('P', 'Proposed'), ('C', 'Complete')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='type',
            field=models.CharField(choices=[('A', 'Assessor'), ('R', 'Reviewer'), ('C', 'Contributor'), ('F', 'Facilitator')], max_length=1),
        ),
    ]
