# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0002_auto_20170327_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatnature',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='threatnature',
            name='stresses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='threatnature',
            name='severity',
            field=models.CharField(blank=True, choices=[('EX', 'Very Rapid Declines'), ('SE', 'Rapid Declines'), ('MO', 'Slow, Significant Declines'), ('SL', 'Causing/Could cause fluctuations'), ('NG', 'Negligible declines'), ('NO', 'No decline'), ('UN', 'Unknown')], default='UN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='threatnature',
            name='timing',
            field=models.CharField(blank=True, choices=[('UR', 'Past, Unlikely to return'), ('LR', 'Past, Likely to return'), ('ON', 'Ongoing'), ('FU', 'Future'), ('PO', 'Potential'), ('UN', 'Unknown')], default='UN', max_length=2, null=True),
        ),
    ]
