# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0003_auto_20170201_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatnature',
            name='impact',
        ),
        migrations.AddField(
            model_name='threatnature',
            name='severity',
            field=models.CharField(blank=True, choices=[('EX', 'Extremely severe'), ('SE', 'Severe'), ('MO', 'Moderate'), ('SL', 'Slight'), ('NO', 'No decline'), ('UN', 'Unknown')], default='UN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='threatnature',
            name='timing',
            field=models.CharField(blank=True, choices=[('PA', 'Past'), ('UR', 'Past, Unlikely to return'), ('LR', 'Past, Likely to return'), ('ON', 'Ongoing'), ('FU', 'Future'), ('PO', 'Potential'), ('UN', 'Unknown')], default='UN', max_length=2, null=True),
        ),
    ]
