# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_reference_bibtex'),
        ('redlist', '0004_auto_20170202_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='references',
            field=models.ManyToManyField(blank=True, null=True, to='biblio.Reference'),
        ),
    ]
