# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0005_assessment_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='references',
            field=models.ManyToManyField(blank=True, to='biblio.Reference'),
        ),
    ]
