# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0006_auto_20170202_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['type', 'weight']},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='redlist_category',
            field=models.CharField(choices=[('EX', 'Extinct (EX)'), ('EW', 'Extinct in the Wild (EW)'), ('CR', 'Critically Endangered (CR)'), ('EN', 'Endangered (EN)'), ('VU', 'Vulnerable (VU)'), ('NT', 'Near Threatened (NT)'), ('LC', 'Least Concern (LC)'), ('DD', 'Data Deficient (DD)'), ('NE', 'Not Evaluated (NE)')], max_length=2),
        ),
    ]
