# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0007_auto_20170207_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='conservation_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='population_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='research_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='threats_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='use_trade_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='change_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='rationale',
            field=models.TextField(blank=True),
        ),
    ]
