# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-14 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0008_auto_20170210_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['date']},
        ),
    ]
