# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0009_auto_20170214_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='distribution_narrative',
            field=models.TextField(blank=True),
        ),
    ]
