# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlist', '0010_assessment_distribution_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='population_trend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
