# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 11:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
                ('bibtex', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('authors', models.ManyToManyField(blank=True, through='biblio.Authorship', to='people.Person')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_biblio.reference_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='authorship',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Reference'),
        ),
    ]
