# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20160915_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='bibtex',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=''),
            preserve_default=False,
        ),
    ]
