# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 13:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_reference_bibtex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='bibtex',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
