# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_auto_20170202_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
