# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 07:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=200, null=True)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=200)),
                ('lifetime', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
            ],
        ),
    ]
