# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
