# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=300),
        ),
    ]
