# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 07:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxa.Taxon')),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='behaviour',
        ),
        migrations.RemoveField(
            model_name='info',
            name='distribution_description',
        ),
        migrations.RemoveField(
            model_name='info',
            name='habitat_ecology',
        ),
        migrations.RemoveField(
            model_name='info',
            name='identification',
        ),
        migrations.AddField(
            model_name='info',
            name='diagnostics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='habitat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='movement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='reproduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='trophic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='uses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='altitude_or_depth_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='morphology',
            field=models.TextField(blank=True),
        ),
    ]
