# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldistribution',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio.Reference'),
        ),
    ]
