# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-22 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0002_auto_20170315_0958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generaldistribution',
            unique_together=set([]),
        ),
    ]
