# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0004_auto_20160916_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonname',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='taxa.Taxon'),
        ),
        migrations.AlterField(
            model_name='description',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='taxa.Taxon'),
        ),
        migrations.AlterField(
            model_name='generaldistribution',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_distributions', to='taxa.Taxon'),
        ),
        migrations.AlterField(
            model_name='image',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='taxa.Taxon'),
        ),
        migrations.AlterField(
            model_name='info',
            name='taxon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='taxa.Taxon'),
        ),
    ]
