# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0005_auto_20160921_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='slug',
            field=models.SlugField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
