# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 13:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0006_taxon_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='info',
            old_name='habitat',
            new_name='habitat_narrative',
        ),
        migrations.AddField(
            model_name='generaldistribution',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='age_units',
            field=models.CharField(blank=True, choices=[('Y', 'Years'), ('M', 'Months'), ('D', 'Days'), ('H', 'Hours')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='average_fecundity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='birth_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='congregatory',
            field=models.CharField(blank=True, choices=[('CO', 'Congregatroy'), ('DI', 'Dispersive'), ('CY', 'Congregatory year round')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='generational_length',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='generational_length_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='gestation_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='longevity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='maturity_age_female',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='maturity_age_male',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='maturity_size_female',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='maturity_size_male',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='max_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='migration_patterns',
            field=models.CharField(blank=True, choices=[('FM', 'Full migrant'), ('AM', 'Altitudinal migrant'), ('NM', 'Not a migrant'), ('NO', 'Nomadic'), ('UN', 'Unknown')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='natural_mortality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='reproductive_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='reproductive_periodicity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='reproductive_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('O', 'Egg laying'), ('V', 'Live birth'), ('P', 'Parthenogenesis'), ('F', 'Free living larvae'), ('W', 'Water breeding')], max_length=1, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='info',
            name='size_units',
            field=models.CharField(blank=True, choices=[('CM', 'CM'), ('MM', 'MM'), ('M', 'M')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='generaldistribution',
            name='residency_status',
            field=models.CharField(choices=[('END', 'National endemic'), ('IND', 'Indigenous'), ('NAT', 'Native'), ('ALN', 'Alien/introduced'), ('INV', 'Invasive'), ('VAG', 'Vagrant'), ('NEN', 'Near endemic'), ('EXT', 'Extinct'), ('UNK', 'Unknown')], max_length=3),
        ),
        migrations.AddField(
            model_name='info',
            name='habitats',
            field=models.ManyToManyField(blank=True, help_text='<strong>Start typing to search through options.</strong> ', to='taxa.Habitat'),
        ),
    ]
