# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0008_taxon_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldistribution',
            name='residency_status',
            field=models.CharField(blank=True, choices=[('END', 'National endemic'), ('IND', 'Indigenous'), ('NAT', 'Native'), ('ALN', 'Alien/introduced'), ('INV', 'Invasive'), ('VAG', 'Vagrant'), ('NEN', 'Near endemic'), ('EXT', 'Extinct'), ('UNK', 'Unknown')], max_length=3, null=True),
        ),
    ]
