# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 08:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0009_auto_20170131_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='congregatory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('CO', 'Congregatroy'), ('DI', 'Dispersive'), ('CY', 'Congregatory year round')], max_length=2, null=True), blank=True, null=True, size=None),
        ),
    ]
