# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0010_auto_20170203_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='birth_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='maturity_size_female',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='maturity_size_male',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='max_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
