# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0011_auto_20170203_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='average_fecundity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='natural_mortality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
