# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0012_auto_20170203_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldistribution',
            name='level',
            field=models.CharField(blank=True, choices=[('C', 'Country'), ('P', 'Province'), ('D', 'District'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
