# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0013_generaldistribution_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonname',
            unique_together=set([('taxon', 'name', 'language')]),
        ),
    ]
