# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0014_auto_20170210_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldistribution',
            name='descripton',
            field=models.TextField(blank=True),
        ),
    ]
