# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-19 09:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0017_auto_20170219_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldistribution',
            name='distribution_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
