# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-19 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0018_auto_20170219_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='distribution',
        ),
    ]
