# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0019_remove_info_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='uses',
        ),
        migrations.AlterUniqueTogether(
            name='taxon',
            unique_together=set([('name', 'parent', 'rank')]),
        ),
    ]
